# Common
spring.application.name=mddapi
server.servlet.context-path=/api
# Jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false